dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libevent-dev
      - doxygen
      - xorg-dev
      - libglu1-mesa-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc -v && g++ -v
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test