dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libsdl2-2.0-0
      - libsdl2-dev
      - libsdl2-gfx-dev
      - libsdl2-image-2.0-0
      - libsdl2-image-dev
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libsdl2-net-dev
      - libsdl2-ttf-2.0-0
      - libsdl2-ttf-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc -v && g++ -v
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test